version: '1.0'
services:
  webservice:
    container_name: "PHP-SERVER"
    build: './build/php/'
    volumes:
      - .:/var/www/html
    ports:
      - 90:80
    depends_on:
      - mysql-srv
  mysql-srv:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quizz
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3396:3306"